services:
  apollo-router:
    image: ghcr.io/apollographql/router:v2.0.0
    volumes:
      - ./supergraph-schema.graphql:/dist/supergraph-schema.graphql
    command: ["--dev", "-s", "supergraph-schema.graphql", "--log", "info"]
    tty: true
    networks:
      - backend
    labels:
      - "traefik.http.routers.apollo.rule=HostRegexp(`api\\..+`)"
      - "traefik.http.services.apollo-router.loadbalancer.server.port=4000"
