services:
  apollo-router:
    image: ghcr.io/apollographql/router:v2.0.0
    volumes:
      - ./supergraph-schema.graphql:/dist/supergraph-schema.graphql
      - ./config.yaml:/dist/config.yaml
    command: [
        "--dev",
        "-s",
        "supergraph-schema.graphql",
        "--log",
        "info",
        "--config",
        "config.yaml",
        # "--port",
        # "4000",
      ]
    tty: true
    networks:
      - backend
    labels:
      - "traefik.http.routers.apollo.rule=HostRegexp(`^(?:\\p{L}+|(\\p{L}+\\.\\p{L}{2,3})|((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4})$`)"
      - "traefik.http.services.apollo-router.loadbalancer.server.port=4000"
