supergraph:
  # The socket address and port to listen on
  listen: 0.0.0.0:4000
traffic_shaping:
  subgraphs:
    products:
      timeout: 10000s
  router:
    timeout: 10000s

cors:
  allow_any_origin: true
