name: findit

include:
  - elk/compose.yaml
  - apollo/compose.yaml
  - brand-service/compose.prod.yaml
  - category-service/compose.prod.yaml
  - product-service/compose.prod.yaml

services:
  traefik:
    image: "traefik:v3.3"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true "
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend
      - analytics

networks:
  backend:
  analytics:

volumes:
  data:
